### ISSUE TITLE
vispy-could-not-import-backend

### ISSUE THREAD

**Issue by edisonchensy** [edisonchensy/vispy-could-not-import-backend#1]
I AM USING PYCHARM AND I'VE ALREADY INSTALL NUMPY, MKL, VISPY...
BUT I STILL GET THIS ERROR, CAN SOMEONE HELP ME? HOW TO SOLVE THIS? 

Traceback (most recent call last):
  File "/home/Edison/SSD-6D/ssd-6d-master/rendering/utils.py", line 18, in <module>
    from rendering.renderer import Renderer
  File "/home/Edison/SSD-6D/ssd-6d-master/rendering/renderer.py", line 8, in <module>
    app.use_app('pyglet')   # Set backend
  File "/home/Edison/anaconda3/lib/python3.6/site-packages/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/home/Edison/anaconda3/lib/python3.6/site-packages/vispy/app/application.py", line 49, in __init__
    self._use(backend_name)
  File "/home/Edison/anaconda3/lib/python3.6/site-packages/vispy/app/application.py", line 223, in _use
    raise RuntimeError(msg)
RuntimeError: Could not import backend "Pyglet":
Cannot connect to "None"

Process finished with exit code 1

**Comment by Qiiiiiiiiii** [comment]
Hi，
I try to run SSD-6Dpose code and get the same error. Could you please tell me how do you solve it?
Thanks.

**Comment by edisonchensy** [comment]
@Qiiiiiiiiii  I just changed my operating system from ubuntu 14.04 to ubuntu 16.04. Have you pip install pyglet and pyfile?

**Comment by Qiiiiiiiiii** [comment]
@edisonchensy Yes, I have install pyglet. But I use the server with other people together so that I can't change my operating system. So is there any other solution ?
